pool:
  name: 'Azure Pipelines'
trigger:
- master
variables:
  TargetFramework: 'net8.0'
  BuildConfiguration: 'Release'
  DockerImageName: 'asia-south1-docker.pkg.dev/task-mgmt-433215/task-mgmt-registry/BackEndAPI'

steps:
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    projects: './BackEndAPI/BackEndAPI.csproj'
    publishWebProjects: false
    command: publish
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
    ArtifactName: '_TaskManagement'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: '_TaskManagement'
    downloadPath: '$(System.ArtifactsDirectory)'